spring.application.name=test
server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=roshka_test;encrypt=true;trustServerCertificate=true
spring.datasource.username=test
spring.datasource.password=test
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
rest.openapi.dev-url=http://localhost:8080
rest.openapi.prod-url=http://localhost:8080
